### ISSUE TITLE
KDE algorithm overfitting will have a risk of exposing real distribution of data

### ISSUE THREAD

**Issue by Adonais0** [tl-its-umich-edu/myla-depersonalizer#38]
As was discussed yesterday, if the KDE distribution fits the original distribution too close, it'll have a risk of exposing original data distribution. We might want to adjust a little bit the `bandwidth` of the algorithm to smooth the distribution and avoid over-fitting.

**Comment by jonespm** [comment]
I think this is going to end up getting fixed by other issues like #47 and #48 so closing
